# Game
BLOCK_SIZE = 40
BLOCK_NUMBER = 20
WIDTH = BLOCK_SIZE * BLOCK_NUMBER
MIDDLE_POS = WIDTH / 2
FPS = 60
BACKGROUND_COLOR = (45, 45, 45)
GAME_UPDATE_TIME = 100

# Images
SNAKE_IMAGE_PATH = "Graphics/snake4.png"
SNAKE_IMAGE_POS = (MIDDLE_POS, MIDDLE_POS)
SNAKE_IMAGE_SCALE = 0.25

# Text
TEXT_FONT_PATH = "Fonts/PressStart2P-Regular.ttf"

BIG_FONT_SIZE = 60
NORMAL_FONT_SIZE = 30

TITLE_TEXT = "Snake Game"
TITLE_POS = (MIDDLE_POS, 200)
TITLE_COLOR = (0,255,0)

PLAY_TEXT = "Press [SPACE] to play"
PLAY_POS = (MIDDLE_POS, 600)
PLAY_COLOR = (255,255,255)

SCORE_TEXT = "SCORE: "
SCORE_POS = (MIDDLE_POS, MIDDLE_POS)
SCORE_COLOR = (255,255,255)


# Snake
SNAKE_COLOR = (0,255,0)

# Fruit
FRUIT_COLOR = (255,0,0)